# Generated by Django 3.2.3 on 2022-02-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_binary',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
